config {
  type: "table",
  schema: "dtf_ads_reporting",
  name: "unified_ad_data",
  database: "liquid-fort-401013",
  bigquery: {
    partitionBy: "date"
  },
  tags: ["daily"]
}

CREATE OR REPLACE TABLE `liquid-fort-401013.dtf_ads_reporting_ad_group_lvl.unified_ad_data` AS
SELECT *
FROM `liquid-fort-401013.dtf_ads_reporting_ad_group_lvl.google_ads_unified_ad_group`
UNION ALL
SELECT *
FROM `liquid-fort-401013.dtf_ads_reporting_ad_group_lvl.meta_unified_ad_group`